### ISSUE TITLE
Change white text buttons on white background ( video button) 

### ISSUE THREAD

**Issue by YalorMewn** [Giveth/wall-of-fame#47] opened 2018-04-11 16:41 UTC
The buttons on the preview page labeled: **Firebase and Share** are white with white lining. The background is also white. Some of the videos are a smaller size in the thumbnail than others so this white text spills over onto the white background and makes it impossible to see. 

Please see the below screenshot
<img width="413" alt="screen shot 2018-04-11 at 6 03 50 pm" src="https://user-images.githubusercontent.com/34845103/38630645-d68ec32a-3db7-11e8-8d39-6e8281350734.png">

**Comment by deamme** [comment] 2018-04-11 22:05
We could fix it by changing colours but the root of the problem is that the contents can't be contained within the video in certain cases. I don't see an easy fix that would make everything look nice.

**Comment by deamme** [comment] 2018-07-27 11:07
Fixed with the new remake

**Closed by deamme** 2018-07-27 11:07 UTC
