### ISSUE TITLE
In Josh's video the pop up won't show so i can't play it 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/wall-of-fame#50] opened 2018-04-20 23:45 UTC
I'm on a mac and chrome 

In the normal desktop view I cant see the button to click
<img width="453" alt="screen shot 2018-04-21 at 1 07 09 am" src="https://user-images.githubusercontent.com/14945613/39077190-730d0e10-4500-11e8-8858-e52c1acce3c6.png">

and in a smaller view I can see the button but its not clickable
<img width="1440" alt="screen shot 2018-04-21 at 1 42 01 am" src="https://user-images.githubusercontent.com/14945613/39077910-b214459c-4505-11e8-93bf-e7d19f90415e.png">

**Comment by deamme** [comment] 2018-04-21 13:57
Yes, this issue is related to #47. I don't have an easy fix for this because the content is dynamic and will therefor not work for every window size. The solution that would fix the root cause of the problem would be redesigning the cards, so the content is shown somewhere else e.g. in a modal when clicking on a video.

**Comment by deamme** [comment] 2018-07-27 11:07
Fixed with the new remake

**Closed by deamme** 2018-07-27 11:07 UTC
